INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F600','😀','grinning face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F603','😃','grinning face with big eyes');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F604','😄','grinning face with smiling eyes');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F601','😁','beaming face with smiling eyes');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F606','😆','grinning squinting face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F605','😅','grinning face with sweat');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F923','🤣','rolling on the floor laughing');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F602','😂','face with tears of joy');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F642','🙂','slightly smiling face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F643','🙃','upside-down face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F609','😉','winking face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F60A','😊','smiling face with smiling eyes');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F607','😇','smiling face with halo');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F970','🥰','smiling face with hearts');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F60D','😍','smiling face with heart-eyes');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F929','🤩','star-struck');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F618','😘','face blowing a kiss');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F617','😗','kissing face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('263A','☺','smiling face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F61A','😚','kissing face with closed eyes');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F619','😙','kissing face with smiling eyes');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F60B','😋','face savoring food');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F61B','😛','face with tongue');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F61C','😜','winking face with tongue');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F92A','🤪','zany face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F61D','😝','squinting face with tongue');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F911','🤑','money-mouth face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F917','🤗','hugging face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F92D','🤭','face with hand over mouth');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F92B','🤫','shushing face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F914','🤔','thinking face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F910','🤐','zipper-mouth face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F928','🤨','face with raised eyebrow');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F610','😐','neutral face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F611','😑','expressionless face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F636','😶','face without mouth');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F60F','😏','smirking face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F612','😒','unamused face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F644','🙄','face with rolling eyes');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F62C','😬','grimacing face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F925','🤥','lying face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F60C','😌','relieved face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F614','😔','pensive face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F62A','😪','sleepy face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F924','🤤','drooling face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F634','😴','sleeping face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F637','😷','face with medical mask');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F912','🤒','face with thermometer');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F915','🤕','face with head-bandage');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F922','🤢','nauseated face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F92E','🤮','face vomiting');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F927','🤧','sneezing face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F975','🥵','hot face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F976','🥶','cold face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F974','🥴','woozy face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F635','😵','dizzy face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F92F','🤯','exploding head');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F920','🤠','cowboy hat face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F973','🥳','partying face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F60E','😎','smiling face with sunglasses');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F913','🤓','nerd face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F9D0','🧐','face with monocle');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F615','😕','confused face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F61F','😟','worried face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F641','🙁','slightly frowning face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('2639','☹','frowning face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F62E','😮','face with open mouth');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F62F','😯','hushed face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F632','😲','astonished face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F633','😳','flushed face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F97A','🥺','pleading face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F626','😦','frowning face with open mouth');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F627','😧','anguished face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F628','😨','fearful face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F630','😰','anxious face with sweat');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F625','😥','sad but relieved face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F622','😢','crying face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F62D','😭','loudly crying face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F631','😱','face screaming in fear');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F616','😖','confounded face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F623','😣','persevering face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F61E','😞','disappointed face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F613','😓','downcast face with sweat');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F629','😩','weary face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F62B','😫','tired face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F971','🥱','⊛ yawning face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F624','😤','face with steam from nose');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F621','😡','pouting face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F620','😠','angry face');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F92C','🤬','face with symbols on mouth');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F608','😈','smiling face with horns');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F47F','👿','angry face with horns');
INSERT INTO reaction(`unicode`,`emote_reaction`,`name_reaction`) VALUES ('1F480','💀','skull');
